[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "tcNytcCkuw0hWcKnhNUYPKjE9ocbOMA9"

[auth.auth0]
domain = "dev-cl2h3mmoy5iem2zt.us.auth0.com"
client_id = "GcaQsE6YJ9nFOb092V6ljv4SDgCb1QFM"
client_secret = "_Lr8qHjARwjSw6gYf89do9ztvy6fKbJ_8zjsTrQFLXiBwsABnkvh3rHgLEooGHYn"
server_metadata_url = "https://dev-cl2h3mmoy5iem2zt.us.auth0.com/.well-known/openid-configuration"
client_kwargs = { "prompt" = "login" }

[auth.google]
client_id = "436614098020-c21ksfa6pgu5l51n3gp0kmdcld9u65hj.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
